# {{ Name }}

# VERSION : {{ Version }}

FROM {{ BaseImage }}
# MAINTAINER Your_name, Your_email_address

ADD requirements.txt /home/run/
RUN pip install -r /home/run/requirements.txt

ADD spec.json /home/run/
ADD main.py /home/run/
