# {{ Name }}

# VERSION : {{ Version }}

FROM {{ BaseImage }}
# MAINTAINER Your_name, Your_email_address

ADD install_packages.R /home/run/
RUN /usr/bin/Rscript /home/run/install_packages.R

ADD spec.json /home/run/
ADD main.R /home/run/

