#+TITLE: Base Images

* Why base images?

[[http://docker.io][Docker]] offers revolutiony platform to build, ship containerized images. The official
images may not match our requirements for packaging modules. So, our base images are
design according to following reasons:

Base images provide minimum requirements for specific usage. For example,
=zetdata/cdh:4= are base images for CDH4 hadoop cluster. And =zetdata/sci-python:2.7=
can provide [[http://scikit-learn.org/][scikit-learn]] toolkit for python data scientists.

Can also save bandwith. Of course, you can build your own module from scratch. Docker
offers incremental pulling, which will pull differental images from remote registry
server. So, it may save bandwith and time if we share same base images.

All scripts to build base images are released at [[https://github.com/DataCanvasIO/docker-brew-datacanvas-base][github repo]], and images are pushed to
[[http://index.docker.com][official docker registry]].

* Hierarchy of base images

[[./base-images.svg]]
